### ISSUE TITLE
I'm kicked out of rooms regularly

### ISSUE THREAD

**Issue by enigma9o7** [matrix-org/libera-chat#11]
### Your Matrix ID

@enigma9o7:matrix

### 30 days activity

- [X] I was active in the rooms in the last 30 days

**Comment by enigma9o7** [comment]
Firstly, I had to check I was active in the room in the past 30 days to continue.  I was not.

About a year or so ago, can't remember, I annoyed an element developer, and he made it so I can't join any libera channels.

Will this last forever?

**Comment by progval** [comment]
>  But it seemed like I couldn't post without checking that box. So please fix this so one can post a message without checking the box

click "Don’t see your issue here? Open a blank issue." on https://github.com/matrix-org/libera-chat/issues/new/choose

**Comment by enigma9o7** [comment]
You're kidding me, right?  Do I really need to explain this to you?

That link you offer presents four options.  One of them fit perfectly, I didn't have to look at the small print for other things.  

The problem comes AFTER I tell it I'm kicked out of rooms regularly.  Just fix it so people can post whether they check the 30-day box or not, unless you don't want people who haven't been active for 30 days to be able to post at all.  Nobody's guna back up and find that wierd option, they're just gunna check the box anyway like I did and think to themselves "this is broken, if i dont check the box I can't even continue" like I did.

**Comment by progval** [comment]
Anyway, joining a room counts as activity for the purposes of this question, so you don't have to make a big deal out of it.

**Comment by Half-Shot** [comment]
Hey, thanks for the report.

It sounds like you're banned through [matrix.org](http://matrix.org/)'s code of conduct which the bridge monitors.

If you'd like to appeal, please email [abuse@matrix.org](mailto:abuse@matrix.org)

**Comment by enigma9o7** [comment]
> Anyway, joining a room counts as activity, so you don't have to make a big deal out of it.

Thats the point.  I haven't been able to join any libera rooms, I'm immediately kick out before any activity is possible, and this happens regularly, on any libera channel.



> It sounds like you're banned through [matrix.org](http://matrix.org/)'s code of conduct which the bridge monitors.
> If you'd like to appeal, please email [abuse@matrix.org](mailto:abuse@matrix.org)

Tried that, no response.

**Comment by enigma9o7** [comment]
Any update?  No response from abuse@matrix.org, still kicked out of rooms regularly.  Please resolve.

**Comment by enigma9o7** [comment]
Still no response from abuse@matrix.org, still kicked out of rooms regularly.  Please resolve.

**Comment by enigma9o7** [comment]
Still no response from [abuse@matrix.org](mailto:abuse@matrix.org), as of today, still kicked out of rooms regularly. Please resolve. And keep this issue opened til its resolved, I dunno how to unclose it, but it shouldnt be closed. Writing email is not the correct solution because it doesn't work, no response, even on 2nd attempt.
