### ISSUE TITLE
Plumbing UI shows "Cannot GET /_matrix/provision/v1/static/"

### ISSUE THREAD

**Issue by progval** [matrix-org/libera-chat#31]
Open any room in Element, click "Add widgets, bridges & bots", enable Libera, you get either "Cannot GET /_matrix/provision/v1/static/" or "503 Service Temporarily Unavailable"

Since 2023-07-26 afternoon/evening (europe time)

**Comment by Half-Shot** [comment]
I think you might have gotten unlucky? We've done a few restarts of the bridge service which may have impacted it.

**Comment by progval** [comment]
Indeed, seems to be back.

**Comment by progval** [comment]
actually I'm getting it again

**Comment by Half-Shot** [comment]
I think this is the case when the bridge is updated, but that's expected.
