### ISSUE TITLE
Messages are not making it through the bridge

### ISSUE THREAD

**Issue by Jaoheah** [matrix-org/libera-chat#33]
### Error type

IRC -> Matrix doesn't work

### Status Check

- [X] I checked https://status.matrix.org

### Federation Check

matrix.org

### Your Matrix ID, if you're a Matrix user

@jaoheah:matrix.org

### Room/channel affected

#blendos

### Time of the issue

08:49-12:31

### Anything else?

IRC -> Matrix hasn't worked at all. 

I connected them at around 08:49 UTC and as of 12:32 UTC it still hasn't worked. 

But Matrix -> IRC works fine. 

To explain it more clearly if I send a message in my Matrix room it will appear in the IRC channel, but if I send a message in the IRC channel it won't appear in my Matrix room.

**Comment by progval** [comment]
```json
{
  "content": {
    "blocked": true
  },
  "origin_server_ts": 1691052497901,
  "room_id": "!jKuVSBfuTXtANOrjZV:matrix.org",
  "sender": "@appservice:libera.chat",
  "state_key": "irc.libera.chat #blendos",
  "type": "org.matrix.appservice-irc.connection",
  "unsigned": {},
  "event_id": "$fdHPXI2YF4KhXHpnnwk5WIP_Q6P12mMl-jS9hTGBQpM",
  "user_id": "@appservice:libera.chat"
}
```

in the room state

**Comment by progval** [comment]
Since your room is world-readable anyway, you can disable the privacy filter: https://matrix-org.github.io/matrix-appservice-irc/latest/room_configuration.html#allowunconnectedmatrixusers

**Comment by Jaoheah** [comment]
> Since your room is world-readable anyway, you can disable the privacy filter: https://matrix-org.github.io/matrix-appservice-irc/latest/room_configuration.html#allowunconnectedmatrixusers

How would I do that?

**Comment by progval** [comment]
You need to set `allowUnconnectedMatrixUsers: true` using the instructions higher on the page I linked

**Comment by Jaoheah** [comment]
Would it be like this? I don't have any experience with JSON formatting. 

```JSON
{
  "content": {
    "blocked": true
  },
  "allowUnconnectedMatrixUsers": true,
  "event_id": "$fdHPXI2YF4KhXHpnnwk5WIP_Q6P12mMl-jS9hTGBQpM",
  "origin_server_ts": 1691052497901,
  "room_id": "!jKuVSBfuTXtANOrjZV:matrix.org",
  "sender": "@appservice:libera.chat",
  "state_key": "irc.libera.chat #blendos",
  "type": "org.matrix.appservice-irc.connection",
  "unsigned": {},
  "user_id": "@appservice:libera.chat"
}
```

or would it be like this?

```JSON
{
  "content": {
    "blocked": true,
    "allowUnconnectedMatrixUsers": true
  },
  "event_id": "$fdHPXI2YF4KhXHpnnwk5WIP_Q6P12mMl-jS9hTGBQpM",
  "origin_server_ts": 1691052497901,
  "room_id": "!jKuVSBfuTXtANOrjZV:matrix.org",
  "sender": "@appservice:libera.chat",
  "state_key": "irc.libera.chat #blendos",
  "type": "org.matrix.appservice-irc.connection",
  "unsigned": {},
  "user_id": "@appservice:libera.chat"
}
```
Or would it be something entirely different?

**Comment by progval** [comment]
You are confusing `org.matrix.appservice-irc.config` (the event you have to set to configure the room) with `org.matrix.appservice-irc.connection` (the event the appservice sets to notify you of the status of the room).

You should only set this: ` {"allowUnconnectedMatrixUsers": true}`, as the `org.matrix.appservice-irc.config` state.

**Comment by progval** [comment]
@Jaoheah Note that it's a workaround, and *someone*'s Matrix puppet is not connecting to IRC, so *their* messages are going to be dropped as well
