### ISSUE TITLE
Role of Matrix.org Foundation?

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/libera-chat#9]
I thought the libera.chat bridge was maintained by Element Matrix Services, but this repository description, organisation and README.md all refer to matrix.org?

What is the connection between matrix.org and EMS? Shouldn't this be under @vector-im ?

**Comment by thibaultamartin** [comment]
The Matrix.org Foundation has a service agreement to let EMS handle the hosting of the Libera Chat synapse instance and bridge on its behalf. It's probably worth clarifying in [Libera Chat's FAQ](https://libera.chat/guides/faq#can-i-connect-with-matrix) and on matrix.org.

The new m.org doesn't list bridges operated by the matrix.org foundation, though it would be a nice addition. Eventually it's going to make it to the website, and you can subscribe to https://github.com/matrix-org/matrix.org/issues/1062 to follow activity on that front :)
